[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
allow = [
    "GPL-3.0",
    "AGPL-3.0",
    "LGPL-2.1",
    "MIT",
    "Apache-2.0",
    "MPL-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "CC0-1.0", 
    "Unlicense",
    "Zlib",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["BUSL-1.1"], crate = "surrealdb"},
    { allow = ["BUSL-1.1"], crate = "surrealdb-core"}
]

[licenses.private]
ignore = true
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
