name: CI
permissions:
  contents: read
  actions: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    name: Format, lint, build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: DeterminateSystems/determinate-nix-action@v3

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock', 'Cargo.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 10G

      - name: Check formatting, clippy lint, unit tests & ort version
        run: nix flake check --show-trace
